### ISSUE TITLE
Is it possible to enable automatic updates?

### ISSUE THREAD

**Issue by suujonH** [kamoo1/Kamoo-s-TSM-App#70]
Can it stay in the background and add automatic updates?
Similar to the RaiderIO client, which updates seamlessly without any awareness.

**Comment by kamoo1** [comment]
Hi there!

It's actually something I've thought about but having doubt implementing, due to the increased traffic on the GitHub proxy server deployed for users in China to access.

However, I have removed the default GitHub proxy since the last patch, only sharing it in a group. I think adding it wouldn't be of a big problem now.
